version: '3'

services:
  neo4j:
    image: neo4j:3.5
    hostname: ${NEO4j_NAME}
    container_name: ${NEO4j_NAME}
    ports:
      - 7474:${NEO4j_HTTP}
      - 7473:${NEO4j_HTTPS}
      - 7687:${NEO4j_BOLT}
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
      NEO4J_dbms_unmanaged__extension__classes: org.neo4j.graphql=/graphql
      NEO4J_dbms_memory_heap_max__size: 8G
      # NEO4J_kafka_zookeeper_connect: zookeeper:2181
      # NEO4J_kafka_bootstrap_servers: broker:9093
      NEO4J_dbms_logs_query_threshold: 0s
      NEO4J_dbms_logs_query_enabled: "true"
      NEO4J_cypher_lenient__create__relationship: "true"
      NEO4J_apoc_trigger_enabled: "true"
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,algo.*"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    volumes:
      - ./Dependents/${NEO4j_NAME}/plugins:/plugins
      - ./Dependents/${NEO4j_NAME}/data:/data
      - ./Dependents/${NEO4j_NAME}/conf:/config

  api:
    build: ./api
    hostname: ${GQL_NAME}
    container_name: ${GQL_NAME}
    environment:
      - NEO4J_URI=bolt://${NEO4j_NAME}:7687
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - GRAPHQL_LISTEN_PORT=4002
      - GRAPHQL_URI=http://${GQL_NAME}:4002/graphql
      - 4002:${GQL_PORT}
    volumes:
      - ./schema:/schema
    links:
    - ${NEO4j_NAME}
    depends_on:
    - ${NEO4j_NAME}

volumes:
  schema:
